import "@/styles/globals.css";
import Head from "next/head";
import { Suspense } from "react";
import dynamic from "next/dynamic";

const NullComponent = ({ children }) => <>{children}</>;

const AnimatedCursor = dynamic(() => import("react-animated-cursor"), {
  ssr: false,
});

<AnimatedCursor />;

export default function App({ Component, pageProps }) {
  const Layout = Component.Layout || NullComponent;
  return (
    <>
      <Head>
        <title>Ashish-Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@500&family=Ubuntu:wght@300&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/images/logo.jpg" />
      </Head>

      <Layout>
        <AnimatedCursor
          color="255,255,255"
          innerSize={8}
          outerSize={35}
          innerScale={1}
          outerScale={1.7}
          className="z-[999999999999999]"
          outerAlpha={0}
          outerStyle={{
            border: "3px solid #fff",
          }}
        />
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
